GET http://localhost:3000/simulator/miner-ids HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/simulator/ambient-temp HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/simulator/ambient-temp HTTP/1.1
content-type: application/json

{
    "temperature": 30
}